### ISSUE TITLE
[bug] 2.0.2 Android App Crash

### ISSUE THREAD

**Issue by emicba126** [EasyTier/EasyTier#409]
### 描述问题 / Describe the bug

FATAL EXCEPTION: main
Process: com.kkrainbow.easytier, PID: 16223
java.lang.RuntimeException: Unable to start service com.plugin.vpnservice.TauriVpnService@845fefd with Intent { cmp=com.kkrainbow.easytier/com.plugin.vpnservice.TauriVpnService (has extras) }: java.lang.IllegalArgumentException: Invalid IP addr string
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4674)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2180)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.IllegalArgumentException: Invalid IP addr string
	at com.plugin.vpnservice.TauriVpnService.onStartCommand(SourceFile:385)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4656)
	... 9 more

### 重现步骤 / Reproduction

Crash App when Run Network button, older versions work fine
Maybe variable "Invalid IP addr string"
Android 12

**Comment by emicba126** [comment]
Resolved in 2.0.3, thanks, great project!
